version: '3.8'

services:
  backend:
    build:
      context: ..
      dockerfile: Docker/backend.Dockerfile
    container_name: school-dashboard-backend
    restart: unless-stopped
    environment:
      SPRING_DATASOURCE_USERNAME: sa
      SPRING_DATASOURCE_PASSWORD: ""
      # Uncomment and supply credentials for production use
      # DSB_USERNAME: your-user
      # DSB_PASSWORD: your-pass
    ports:
      - "8080:8080"
    volumes:
      - backend-data:/data
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/dsb/timetables || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  backend-data:
