/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThrowErrorRouteImport } from './routes/throw-error'
import { Route as SetupRouteRouteImport } from './routes/setup/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SetupIndexRouteImport } from './routes/setup/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as SetupPendingRouteImport } from './routes/setup/pending'
import { Route as RueckmeldungDisplayIdRouteImport } from './routes/rueckmeldung/$displayId'
import { Route as DisplayDisplayIdRouteImport } from './routes/display/$displayId'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDisplaysRouteRouteImport } from './routes/admin/displays/route'
import { Route as AdminSurveysIndexRouteImport } from './routes/admin/surveys/index'
import { Route as AdminDisplaysIndexRouteImport } from './routes/admin/displays/index'
import { Route as ApiSurveysSubmissionsRouteImport } from './routes/api/surveys/submissions'
import { Route as ApiSubstitutionPlansRouteImport } from './routes/api/substitution/plans'
import { Route as ApiDisplaysSessionRouteImport } from './routes/api/displays/session'
import { Route as ApiCalendarEventsRouteImport } from './routes/api/calendar/events'
import { Route as ApiAdminSurveysRouteImport } from './routes/api/admin/surveys'
import { Route as AdminDisplaysPendingRouteImport } from './routes/admin/displays/pending'
import { Route as AdminDisplaysDisplayIdRouteImport } from './routes/admin/displays/$displayId'
import { Route as ApiAdminDisplaysRouteRouteImport } from './routes/api/admin/displays/route'
import { Route as ApiDisplaysEnrollmentsIndexRouteImport } from './routes/api/displays/enrollments/index'
import { Route as ApiTransportStopsNearbyRouteImport } from './routes/api/transport/stops/nearby'
import { Route as ApiSurveysDisplaysDisplayIdRouteImport } from './routes/api/surveys/displays/$displayId'
import { Route as ApiDisplaysEnrollmentsRequestIdRouteImport } from './routes/api/displays/enrollments/$requestId'
import { Route as ApiAdminDisplaysEnrollmentCodesRouteImport } from './routes/api/admin/displays/enrollment-codes'
import { Route as ApiAdminDisplaysAuditLogsRouteImport } from './routes/api/admin/displays/audit-logs'
import { Route as ApiAdminAuthMeRouteImport } from './routes/api/admin/auth/me'
import { Route as ApiAdminAuthLogoutRouteImport } from './routes/api/admin/auth/logout'
import { Route as ApiAdminAuthLoginRouteImport } from './routes/api/admin/auth/login'
import { Route as ApiAdminAuthCsrfRouteImport } from './routes/api/admin/auth/csrf'
import { Route as ApiAdminAuthCredentialsRouteImport } from './routes/api/admin/auth/credentials'
import { Route as ApiAdminDisplaysEnrollmentsRouteRouteImport } from './routes/api/admin/displays/enrollments/route'
import { Route as ApiAdminDisplaysDisplayIdRouteRouteImport } from './routes/api/admin/displays/$displayId/route'
import { Route as ApiTransportStopsStopIdDeparturesRouteImport } from './routes/api/transport/stops/$stopId/departures'
import { Route as ApiAdminDisplaysDisplayIdRevokeSessionRouteImport } from './routes/api/admin/displays/$displayId/revoke-session'
import { Route as ApiAdminDisplaysEnrollmentsRequestIdRejectRouteImport } from './routes/api/admin/displays/enrollments/$requestId/reject'
import { Route as ApiAdminDisplaysEnrollmentsRequestIdApproveRouteImport } from './routes/api/admin/displays/enrollments/$requestId/approve'

const ThrowErrorRoute = ThrowErrorRouteImport.update({
  id: '/throw-error',
  path: '/throw-error',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupRouteRoute = SetupRouteRouteImport.update({
  id: '/setup',
  path: '/setup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SetupIndexRoute = SetupIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SetupRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const SetupPendingRoute = SetupPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => SetupRouteRoute,
} as any)
const RueckmeldungDisplayIdRoute = RueckmeldungDisplayIdRouteImport.update({
  id: '/rueckmeldung/$displayId',
  path: '/rueckmeldung/$displayId',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayDisplayIdRoute = DisplayDisplayIdRouteImport.update({
  id: '/display/$displayId',
  path: '/display/$displayId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDisplaysRouteRoute = AdminDisplaysRouteRouteImport.update({
  id: '/displays',
  path: '/displays',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminSurveysIndexRoute = AdminSurveysIndexRouteImport.update({
  id: '/surveys/',
  path: '/surveys/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminDisplaysIndexRoute = AdminDisplaysIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminDisplaysRouteRoute,
} as any)
const ApiSurveysSubmissionsRoute = ApiSurveysSubmissionsRouteImport.update({
  id: '/api/surveys/submissions',
  path: '/api/surveys/submissions',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubstitutionPlansRoute = ApiSubstitutionPlansRouteImport.update({
  id: '/api/substitution/plans',
  path: '/api/substitution/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDisplaysSessionRoute = ApiDisplaysSessionRouteImport.update({
  id: '/api/displays/session',
  path: '/api/displays/session',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarEventsRoute = ApiCalendarEventsRouteImport.update({
  id: '/api/calendar/events',
  path: '/api/calendar/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminSurveysRoute = ApiAdminSurveysRouteImport.update({
  id: '/api/admin/surveys',
  path: '/api/admin/surveys',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDisplaysPendingRoute = AdminDisplaysPendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => AdminDisplaysRouteRoute,
} as any)
const AdminDisplaysDisplayIdRoute = AdminDisplaysDisplayIdRouteImport.update({
  id: '/$displayId',
  path: '/$displayId',
  getParentRoute: () => AdminDisplaysRouteRoute,
} as any)
const ApiAdminDisplaysRouteRoute = ApiAdminDisplaysRouteRouteImport.update({
  id: '/api/admin/displays',
  path: '/api/admin/displays',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiDisplaysEnrollmentsIndexRoute =
  ApiDisplaysEnrollmentsIndexRouteImport.update({
    id: '/api/displays/enrollments/',
    path: '/api/displays/enrollments/',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiTransportStopsNearbyRoute = ApiTransportStopsNearbyRouteImport.update({
  id: '/api/transport/stops/nearby',
  path: '/api/transport/stops/nearby',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSurveysDisplaysDisplayIdRoute =
  ApiSurveysDisplaysDisplayIdRouteImport.update({
    id: '/api/surveys/displays/$displayId',
    path: '/api/surveys/displays/$displayId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiDisplaysEnrollmentsRequestIdRoute =
  ApiDisplaysEnrollmentsRequestIdRouteImport.update({
    id: '/api/displays/enrollments/$requestId',
    path: '/api/displays/enrollments/$requestId',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminDisplaysEnrollmentCodesRoute =
  ApiAdminDisplaysEnrollmentCodesRouteImport.update({
    id: '/enrollment-codes',
    path: '/enrollment-codes',
    getParentRoute: () => ApiAdminDisplaysRouteRoute,
  } as any)
const ApiAdminDisplaysAuditLogsRoute =
  ApiAdminDisplaysAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => ApiAdminDisplaysRouteRoute,
  } as any)
const ApiAdminAuthMeRoute = ApiAdminAuthMeRouteImport.update({
  id: '/api/admin/auth/me',
  path: '/api/admin/auth/me',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthLogoutRoute = ApiAdminAuthLogoutRouteImport.update({
  id: '/api/admin/auth/logout',
  path: '/api/admin/auth/logout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthLoginRoute = ApiAdminAuthLoginRouteImport.update({
  id: '/api/admin/auth/login',
  path: '/api/admin/auth/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthCsrfRoute = ApiAdminAuthCsrfRouteImport.update({
  id: '/api/admin/auth/csrf',
  path: '/api/admin/auth/csrf',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminAuthCredentialsRoute = ApiAdminAuthCredentialsRouteImport.update({
  id: '/api/admin/auth/credentials',
  path: '/api/admin/auth/credentials',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAdminDisplaysEnrollmentsRouteRoute =
  ApiAdminDisplaysEnrollmentsRouteRouteImport.update({
    id: '/enrollments',
    path: '/enrollments',
    getParentRoute: () => ApiAdminDisplaysRouteRoute,
  } as any)
const ApiAdminDisplaysDisplayIdRouteRoute =
  ApiAdminDisplaysDisplayIdRouteRouteImport.update({
    id: '/$displayId',
    path: '/$displayId',
    getParentRoute: () => ApiAdminDisplaysRouteRoute,
  } as any)
const ApiTransportStopsStopIdDeparturesRoute =
  ApiTransportStopsStopIdDeparturesRouteImport.update({
    id: '/api/transport/stops/$stopId/departures',
    path: '/api/transport/stops/$stopId/departures',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiAdminDisplaysDisplayIdRevokeSessionRoute =
  ApiAdminDisplaysDisplayIdRevokeSessionRouteImport.update({
    id: '/revoke-session',
    path: '/revoke-session',
    getParentRoute: () => ApiAdminDisplaysDisplayIdRouteRoute,
  } as any)
const ApiAdminDisplaysEnrollmentsRequestIdRejectRoute =
  ApiAdminDisplaysEnrollmentsRequestIdRejectRouteImport.update({
    id: '/$requestId/reject',
    path: '/$requestId/reject',
    getParentRoute: () => ApiAdminDisplaysEnrollmentsRouteRoute,
  } as any)
const ApiAdminDisplaysEnrollmentsRequestIdApproveRoute =
  ApiAdminDisplaysEnrollmentsRequestIdApproveRouteImport.update({
    id: '/$requestId/approve',
    path: '/$requestId/approve',
    getParentRoute: () => ApiAdminDisplaysEnrollmentsRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/setup': typeof SetupRouteRouteWithChildren
  '/throw-error': typeof ThrowErrorRoute
  '/admin/displays': typeof AdminDisplaysRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/display/$displayId': typeof DisplayDisplayIdRoute
  '/rueckmeldung/$displayId': typeof RueckmeldungDisplayIdRoute
  '/setup/pending': typeof SetupPendingRoute
  '/admin/': typeof AdminIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/api/admin/displays': typeof ApiAdminDisplaysRouteRouteWithChildren
  '/admin/displays/$displayId': typeof AdminDisplaysDisplayIdRoute
  '/admin/displays/pending': typeof AdminDisplaysPendingRoute
  '/api/admin/surveys': typeof ApiAdminSurveysRoute
  '/api/calendar/events': typeof ApiCalendarEventsRoute
  '/api/displays/session': typeof ApiDisplaysSessionRoute
  '/api/substitution/plans': typeof ApiSubstitutionPlansRoute
  '/api/surveys/submissions': typeof ApiSurveysSubmissionsRoute
  '/admin/displays/': typeof AdminDisplaysIndexRoute
  '/admin/surveys/': typeof AdminSurveysIndexRoute
  '/api/admin/displays/$displayId': typeof ApiAdminDisplaysDisplayIdRouteRouteWithChildren
  '/api/admin/displays/enrollments': typeof ApiAdminDisplaysEnrollmentsRouteRouteWithChildren
  '/api/admin/auth/credentials': typeof ApiAdminAuthCredentialsRoute
  '/api/admin/auth/csrf': typeof ApiAdminAuthCsrfRoute
  '/api/admin/auth/login': typeof ApiAdminAuthLoginRoute
  '/api/admin/auth/logout': typeof ApiAdminAuthLogoutRoute
  '/api/admin/auth/me': typeof ApiAdminAuthMeRoute
  '/api/admin/displays/audit-logs': typeof ApiAdminDisplaysAuditLogsRoute
  '/api/admin/displays/enrollment-codes': typeof ApiAdminDisplaysEnrollmentCodesRoute
  '/api/displays/enrollments/$requestId': typeof ApiDisplaysEnrollmentsRequestIdRoute
  '/api/surveys/displays/$displayId': typeof ApiSurveysDisplaysDisplayIdRoute
  '/api/transport/stops/nearby': typeof ApiTransportStopsNearbyRoute
  '/api/displays/enrollments/': typeof ApiDisplaysEnrollmentsIndexRoute
  '/api/admin/displays/$displayId/revoke-session': typeof ApiAdminDisplaysDisplayIdRevokeSessionRoute
  '/api/transport/stops/$stopId/departures': typeof ApiTransportStopsStopIdDeparturesRoute
  '/api/admin/displays/enrollments/$requestId/approve': typeof ApiAdminDisplaysEnrollmentsRequestIdApproveRoute
  '/api/admin/displays/enrollments/$requestId/reject': typeof ApiAdminDisplaysEnrollmentsRequestIdRejectRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/throw-error': typeof ThrowErrorRoute
  '/admin/login': typeof AdminLoginRoute
  '/display/$displayId': typeof DisplayDisplayIdRoute
  '/rueckmeldung/$displayId': typeof RueckmeldungDisplayIdRoute
  '/setup/pending': typeof SetupPendingRoute
  '/admin': typeof AdminIndexRoute
  '/setup': typeof SetupIndexRoute
  '/api/admin/displays': typeof ApiAdminDisplaysRouteRouteWithChildren
  '/admin/displays/$displayId': typeof AdminDisplaysDisplayIdRoute
  '/admin/displays/pending': typeof AdminDisplaysPendingRoute
  '/api/admin/surveys': typeof ApiAdminSurveysRoute
  '/api/calendar/events': typeof ApiCalendarEventsRoute
  '/api/displays/session': typeof ApiDisplaysSessionRoute
  '/api/substitution/plans': typeof ApiSubstitutionPlansRoute
  '/api/surveys/submissions': typeof ApiSurveysSubmissionsRoute
  '/admin/displays': typeof AdminDisplaysIndexRoute
  '/admin/surveys': typeof AdminSurveysIndexRoute
  '/api/admin/displays/$displayId': typeof ApiAdminDisplaysDisplayIdRouteRouteWithChildren
  '/api/admin/displays/enrollments': typeof ApiAdminDisplaysEnrollmentsRouteRouteWithChildren
  '/api/admin/auth/credentials': typeof ApiAdminAuthCredentialsRoute
  '/api/admin/auth/csrf': typeof ApiAdminAuthCsrfRoute
  '/api/admin/auth/login': typeof ApiAdminAuthLoginRoute
  '/api/admin/auth/logout': typeof ApiAdminAuthLogoutRoute
  '/api/admin/auth/me': typeof ApiAdminAuthMeRoute
  '/api/admin/displays/audit-logs': typeof ApiAdminDisplaysAuditLogsRoute
  '/api/admin/displays/enrollment-codes': typeof ApiAdminDisplaysEnrollmentCodesRoute
  '/api/displays/enrollments/$requestId': typeof ApiDisplaysEnrollmentsRequestIdRoute
  '/api/surveys/displays/$displayId': typeof ApiSurveysDisplaysDisplayIdRoute
  '/api/transport/stops/nearby': typeof ApiTransportStopsNearbyRoute
  '/api/displays/enrollments': typeof ApiDisplaysEnrollmentsIndexRoute
  '/api/admin/displays/$displayId/revoke-session': typeof ApiAdminDisplaysDisplayIdRevokeSessionRoute
  '/api/transport/stops/$stopId/departures': typeof ApiTransportStopsStopIdDeparturesRoute
  '/api/admin/displays/enrollments/$requestId/approve': typeof ApiAdminDisplaysEnrollmentsRequestIdApproveRoute
  '/api/admin/displays/enrollments/$requestId/reject': typeof ApiAdminDisplaysEnrollmentsRequestIdRejectRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/setup': typeof SetupRouteRouteWithChildren
  '/throw-error': typeof ThrowErrorRoute
  '/admin/displays': typeof AdminDisplaysRouteRouteWithChildren
  '/admin/login': typeof AdminLoginRoute
  '/display/$displayId': typeof DisplayDisplayIdRoute
  '/rueckmeldung/$displayId': typeof RueckmeldungDisplayIdRoute
  '/setup/pending': typeof SetupPendingRoute
  '/admin/': typeof AdminIndexRoute
  '/setup/': typeof SetupIndexRoute
  '/api/admin/displays': typeof ApiAdminDisplaysRouteRouteWithChildren
  '/admin/displays/$displayId': typeof AdminDisplaysDisplayIdRoute
  '/admin/displays/pending': typeof AdminDisplaysPendingRoute
  '/api/admin/surveys': typeof ApiAdminSurveysRoute
  '/api/calendar/events': typeof ApiCalendarEventsRoute
  '/api/displays/session': typeof ApiDisplaysSessionRoute
  '/api/substitution/plans': typeof ApiSubstitutionPlansRoute
  '/api/surveys/submissions': typeof ApiSurveysSubmissionsRoute
  '/admin/displays/': typeof AdminDisplaysIndexRoute
  '/admin/surveys/': typeof AdminSurveysIndexRoute
  '/api/admin/displays/$displayId': typeof ApiAdminDisplaysDisplayIdRouteRouteWithChildren
  '/api/admin/displays/enrollments': typeof ApiAdminDisplaysEnrollmentsRouteRouteWithChildren
  '/api/admin/auth/credentials': typeof ApiAdminAuthCredentialsRoute
  '/api/admin/auth/csrf': typeof ApiAdminAuthCsrfRoute
  '/api/admin/auth/login': typeof ApiAdminAuthLoginRoute
  '/api/admin/auth/logout': typeof ApiAdminAuthLogoutRoute
  '/api/admin/auth/me': typeof ApiAdminAuthMeRoute
  '/api/admin/displays/audit-logs': typeof ApiAdminDisplaysAuditLogsRoute
  '/api/admin/displays/enrollment-codes': typeof ApiAdminDisplaysEnrollmentCodesRoute
  '/api/displays/enrollments/$requestId': typeof ApiDisplaysEnrollmentsRequestIdRoute
  '/api/surveys/displays/$displayId': typeof ApiSurveysDisplaysDisplayIdRoute
  '/api/transport/stops/nearby': typeof ApiTransportStopsNearbyRoute
  '/api/displays/enrollments/': typeof ApiDisplaysEnrollmentsIndexRoute
  '/api/admin/displays/$displayId/revoke-session': typeof ApiAdminDisplaysDisplayIdRevokeSessionRoute
  '/api/transport/stops/$stopId/departures': typeof ApiTransportStopsStopIdDeparturesRoute
  '/api/admin/displays/enrollments/$requestId/approve': typeof ApiAdminDisplaysEnrollmentsRequestIdApproveRoute
  '/api/admin/displays/enrollments/$requestId/reject': typeof ApiAdminDisplaysEnrollmentsRequestIdRejectRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/setup'
    | '/throw-error'
    | '/admin/displays'
    | '/admin/login'
    | '/display/$displayId'
    | '/rueckmeldung/$displayId'
    | '/setup/pending'
    | '/admin/'
    | '/setup/'
    | '/api/admin/displays'
    | '/admin/displays/$displayId'
    | '/admin/displays/pending'
    | '/api/admin/surveys'
    | '/api/calendar/events'
    | '/api/displays/session'
    | '/api/substitution/plans'
    | '/api/surveys/submissions'
    | '/admin/displays/'
    | '/admin/surveys/'
    | '/api/admin/displays/$displayId'
    | '/api/admin/displays/enrollments'
    | '/api/admin/auth/credentials'
    | '/api/admin/auth/csrf'
    | '/api/admin/auth/login'
    | '/api/admin/auth/logout'
    | '/api/admin/auth/me'
    | '/api/admin/displays/audit-logs'
    | '/api/admin/displays/enrollment-codes'
    | '/api/displays/enrollments/$requestId'
    | '/api/surveys/displays/$displayId'
    | '/api/transport/stops/nearby'
    | '/api/displays/enrollments/'
    | '/api/admin/displays/$displayId/revoke-session'
    | '/api/transport/stops/$stopId/departures'
    | '/api/admin/displays/enrollments/$requestId/approve'
    | '/api/admin/displays/enrollments/$requestId/reject'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/throw-error'
    | '/admin/login'
    | '/display/$displayId'
    | '/rueckmeldung/$displayId'
    | '/setup/pending'
    | '/admin'
    | '/setup'
    | '/api/admin/displays'
    | '/admin/displays/$displayId'
    | '/admin/displays/pending'
    | '/api/admin/surveys'
    | '/api/calendar/events'
    | '/api/displays/session'
    | '/api/substitution/plans'
    | '/api/surveys/submissions'
    | '/admin/displays'
    | '/admin/surveys'
    | '/api/admin/displays/$displayId'
    | '/api/admin/displays/enrollments'
    | '/api/admin/auth/credentials'
    | '/api/admin/auth/csrf'
    | '/api/admin/auth/login'
    | '/api/admin/auth/logout'
    | '/api/admin/auth/me'
    | '/api/admin/displays/audit-logs'
    | '/api/admin/displays/enrollment-codes'
    | '/api/displays/enrollments/$requestId'
    | '/api/surveys/displays/$displayId'
    | '/api/transport/stops/nearby'
    | '/api/displays/enrollments'
    | '/api/admin/displays/$displayId/revoke-session'
    | '/api/transport/stops/$stopId/departures'
    | '/api/admin/displays/enrollments/$requestId/approve'
    | '/api/admin/displays/enrollments/$requestId/reject'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/setup'
    | '/throw-error'
    | '/admin/displays'
    | '/admin/login'
    | '/display/$displayId'
    | '/rueckmeldung/$displayId'
    | '/setup/pending'
    | '/admin/'
    | '/setup/'
    | '/api/admin/displays'
    | '/admin/displays/$displayId'
    | '/admin/displays/pending'
    | '/api/admin/surveys'
    | '/api/calendar/events'
    | '/api/displays/session'
    | '/api/substitution/plans'
    | '/api/surveys/submissions'
    | '/admin/displays/'
    | '/admin/surveys/'
    | '/api/admin/displays/$displayId'
    | '/api/admin/displays/enrollments'
    | '/api/admin/auth/credentials'
    | '/api/admin/auth/csrf'
    | '/api/admin/auth/login'
    | '/api/admin/auth/logout'
    | '/api/admin/auth/me'
    | '/api/admin/displays/audit-logs'
    | '/api/admin/displays/enrollment-codes'
    | '/api/displays/enrollments/$requestId'
    | '/api/surveys/displays/$displayId'
    | '/api/transport/stops/nearby'
    | '/api/displays/enrollments/'
    | '/api/admin/displays/$displayId/revoke-session'
    | '/api/transport/stops/$stopId/departures'
    | '/api/admin/displays/enrollments/$requestId/approve'
    | '/api/admin/displays/enrollments/$requestId/reject'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  SetupRouteRoute: typeof SetupRouteRouteWithChildren
  ThrowErrorRoute: typeof ThrowErrorRoute
  DisplayDisplayIdRoute: typeof DisplayDisplayIdRoute
  RueckmeldungDisplayIdRoute: typeof RueckmeldungDisplayIdRoute
  ApiAdminDisplaysRouteRoute: typeof ApiAdminDisplaysRouteRouteWithChildren
  ApiAdminSurveysRoute: typeof ApiAdminSurveysRoute
  ApiCalendarEventsRoute: typeof ApiCalendarEventsRoute
  ApiDisplaysSessionRoute: typeof ApiDisplaysSessionRoute
  ApiSubstitutionPlansRoute: typeof ApiSubstitutionPlansRoute
  ApiSurveysSubmissionsRoute: typeof ApiSurveysSubmissionsRoute
  ApiAdminAuthCredentialsRoute: typeof ApiAdminAuthCredentialsRoute
  ApiAdminAuthCsrfRoute: typeof ApiAdminAuthCsrfRoute
  ApiAdminAuthLoginRoute: typeof ApiAdminAuthLoginRoute
  ApiAdminAuthLogoutRoute: typeof ApiAdminAuthLogoutRoute
  ApiAdminAuthMeRoute: typeof ApiAdminAuthMeRoute
  ApiDisplaysEnrollmentsRequestIdRoute: typeof ApiDisplaysEnrollmentsRequestIdRoute
  ApiSurveysDisplaysDisplayIdRoute: typeof ApiSurveysDisplaysDisplayIdRoute
  ApiTransportStopsNearbyRoute: typeof ApiTransportStopsNearbyRoute
  ApiDisplaysEnrollmentsIndexRoute: typeof ApiDisplaysEnrollmentsIndexRoute
  ApiTransportStopsStopIdDeparturesRoute: typeof ApiTransportStopsStopIdDeparturesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/throw-error': {
      id: '/throw-error'
      path: '/throw-error'
      fullPath: '/throw-error'
      preLoaderRoute: typeof ThrowErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup': {
      id: '/setup'
      path: '/setup'
      fullPath: '/setup'
      preLoaderRoute: typeof SetupRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/setup/': {
      id: '/setup/'
      path: '/'
      fullPath: '/setup/'
      preLoaderRoute: typeof SetupIndexRouteImport
      parentRoute: typeof SetupRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/setup/pending': {
      id: '/setup/pending'
      path: '/pending'
      fullPath: '/setup/pending'
      preLoaderRoute: typeof SetupPendingRouteImport
      parentRoute: typeof SetupRouteRoute
    }
    '/rueckmeldung/$displayId': {
      id: '/rueckmeldung/$displayId'
      path: '/rueckmeldung/$displayId'
      fullPath: '/rueckmeldung/$displayId'
      preLoaderRoute: typeof RueckmeldungDisplayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/$displayId': {
      id: '/display/$displayId'
      path: '/display/$displayId'
      fullPath: '/display/$displayId'
      preLoaderRoute: typeof DisplayDisplayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/displays': {
      id: '/admin/displays'
      path: '/displays'
      fullPath: '/admin/displays'
      preLoaderRoute: typeof AdminDisplaysRouteRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/surveys/': {
      id: '/admin/surveys/'
      path: '/surveys'
      fullPath: '/admin/surveys/'
      preLoaderRoute: typeof AdminSurveysIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/displays/': {
      id: '/admin/displays/'
      path: '/'
      fullPath: '/admin/displays/'
      preLoaderRoute: typeof AdminDisplaysIndexRouteImport
      parentRoute: typeof AdminDisplaysRouteRoute
    }
    '/api/surveys/submissions': {
      id: '/api/surveys/submissions'
      path: '/api/surveys/submissions'
      fullPath: '/api/surveys/submissions'
      preLoaderRoute: typeof ApiSurveysSubmissionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/substitution/plans': {
      id: '/api/substitution/plans'
      path: '/api/substitution/plans'
      fullPath: '/api/substitution/plans'
      preLoaderRoute: typeof ApiSubstitutionPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/displays/session': {
      id: '/api/displays/session'
      path: '/api/displays/session'
      fullPath: '/api/displays/session'
      preLoaderRoute: typeof ApiDisplaysSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/events': {
      id: '/api/calendar/events'
      path: '/api/calendar/events'
      fullPath: '/api/calendar/events'
      preLoaderRoute: typeof ApiCalendarEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/surveys': {
      id: '/api/admin/surveys'
      path: '/api/admin/surveys'
      fullPath: '/api/admin/surveys'
      preLoaderRoute: typeof ApiAdminSurveysRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/displays/pending': {
      id: '/admin/displays/pending'
      path: '/pending'
      fullPath: '/admin/displays/pending'
      preLoaderRoute: typeof AdminDisplaysPendingRouteImport
      parentRoute: typeof AdminDisplaysRouteRoute
    }
    '/admin/displays/$displayId': {
      id: '/admin/displays/$displayId'
      path: '/$displayId'
      fullPath: '/admin/displays/$displayId'
      preLoaderRoute: typeof AdminDisplaysDisplayIdRouteImport
      parentRoute: typeof AdminDisplaysRouteRoute
    }
    '/api/admin/displays': {
      id: '/api/admin/displays'
      path: '/api/admin/displays'
      fullPath: '/api/admin/displays'
      preLoaderRoute: typeof ApiAdminDisplaysRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/displays/enrollments/': {
      id: '/api/displays/enrollments/'
      path: '/api/displays/enrollments'
      fullPath: '/api/displays/enrollments/'
      preLoaderRoute: typeof ApiDisplaysEnrollmentsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/transport/stops/nearby': {
      id: '/api/transport/stops/nearby'
      path: '/api/transport/stops/nearby'
      fullPath: '/api/transport/stops/nearby'
      preLoaderRoute: typeof ApiTransportStopsNearbyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/surveys/displays/$displayId': {
      id: '/api/surveys/displays/$displayId'
      path: '/api/surveys/displays/$displayId'
      fullPath: '/api/surveys/displays/$displayId'
      preLoaderRoute: typeof ApiSurveysDisplaysDisplayIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/displays/enrollments/$requestId': {
      id: '/api/displays/enrollments/$requestId'
      path: '/api/displays/enrollments/$requestId'
      fullPath: '/api/displays/enrollments/$requestId'
      preLoaderRoute: typeof ApiDisplaysEnrollmentsRequestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/displays/enrollment-codes': {
      id: '/api/admin/displays/enrollment-codes'
      path: '/enrollment-codes'
      fullPath: '/api/admin/displays/enrollment-codes'
      preLoaderRoute: typeof ApiAdminDisplaysEnrollmentCodesRouteImport
      parentRoute: typeof ApiAdminDisplaysRouteRoute
    }
    '/api/admin/displays/audit-logs': {
      id: '/api/admin/displays/audit-logs'
      path: '/audit-logs'
      fullPath: '/api/admin/displays/audit-logs'
      preLoaderRoute: typeof ApiAdminDisplaysAuditLogsRouteImport
      parentRoute: typeof ApiAdminDisplaysRouteRoute
    }
    '/api/admin/auth/me': {
      id: '/api/admin/auth/me'
      path: '/api/admin/auth/me'
      fullPath: '/api/admin/auth/me'
      preLoaderRoute: typeof ApiAdminAuthMeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/logout': {
      id: '/api/admin/auth/logout'
      path: '/api/admin/auth/logout'
      fullPath: '/api/admin/auth/logout'
      preLoaderRoute: typeof ApiAdminAuthLogoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/login': {
      id: '/api/admin/auth/login'
      path: '/api/admin/auth/login'
      fullPath: '/api/admin/auth/login'
      preLoaderRoute: typeof ApiAdminAuthLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/csrf': {
      id: '/api/admin/auth/csrf'
      path: '/api/admin/auth/csrf'
      fullPath: '/api/admin/auth/csrf'
      preLoaderRoute: typeof ApiAdminAuthCsrfRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/auth/credentials': {
      id: '/api/admin/auth/credentials'
      path: '/api/admin/auth/credentials'
      fullPath: '/api/admin/auth/credentials'
      preLoaderRoute: typeof ApiAdminAuthCredentialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/displays/enrollments': {
      id: '/api/admin/displays/enrollments'
      path: '/enrollments'
      fullPath: '/api/admin/displays/enrollments'
      preLoaderRoute: typeof ApiAdminDisplaysEnrollmentsRouteRouteImport
      parentRoute: typeof ApiAdminDisplaysRouteRoute
    }
    '/api/admin/displays/$displayId': {
      id: '/api/admin/displays/$displayId'
      path: '/$displayId'
      fullPath: '/api/admin/displays/$displayId'
      preLoaderRoute: typeof ApiAdminDisplaysDisplayIdRouteRouteImport
      parentRoute: typeof ApiAdminDisplaysRouteRoute
    }
    '/api/transport/stops/$stopId/departures': {
      id: '/api/transport/stops/$stopId/departures'
      path: '/api/transport/stops/$stopId/departures'
      fullPath: '/api/transport/stops/$stopId/departures'
      preLoaderRoute: typeof ApiTransportStopsStopIdDeparturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/admin/displays/$displayId/revoke-session': {
      id: '/api/admin/displays/$displayId/revoke-session'
      path: '/revoke-session'
      fullPath: '/api/admin/displays/$displayId/revoke-session'
      preLoaderRoute: typeof ApiAdminDisplaysDisplayIdRevokeSessionRouteImport
      parentRoute: typeof ApiAdminDisplaysDisplayIdRouteRoute
    }
    '/api/admin/displays/enrollments/$requestId/reject': {
      id: '/api/admin/displays/enrollments/$requestId/reject'
      path: '/$requestId/reject'
      fullPath: '/api/admin/displays/enrollments/$requestId/reject'
      preLoaderRoute: typeof ApiAdminDisplaysEnrollmentsRequestIdRejectRouteImport
      parentRoute: typeof ApiAdminDisplaysEnrollmentsRouteRoute
    }
    '/api/admin/displays/enrollments/$requestId/approve': {
      id: '/api/admin/displays/enrollments/$requestId/approve'
      path: '/$requestId/approve'
      fullPath: '/api/admin/displays/enrollments/$requestId/approve'
      preLoaderRoute: typeof ApiAdminDisplaysEnrollmentsRequestIdApproveRouteImport
      parentRoute: typeof ApiAdminDisplaysEnrollmentsRouteRoute
    }
  }
}

interface AdminDisplaysRouteRouteChildren {
  AdminDisplaysDisplayIdRoute: typeof AdminDisplaysDisplayIdRoute
  AdminDisplaysPendingRoute: typeof AdminDisplaysPendingRoute
  AdminDisplaysIndexRoute: typeof AdminDisplaysIndexRoute
}

const AdminDisplaysRouteRouteChildren: AdminDisplaysRouteRouteChildren = {
  AdminDisplaysDisplayIdRoute: AdminDisplaysDisplayIdRoute,
  AdminDisplaysPendingRoute: AdminDisplaysPendingRoute,
  AdminDisplaysIndexRoute: AdminDisplaysIndexRoute,
}

const AdminDisplaysRouteRouteWithChildren =
  AdminDisplaysRouteRoute._addFileChildren(AdminDisplaysRouteRouteChildren)

interface AdminRouteRouteChildren {
  AdminDisplaysRouteRoute: typeof AdminDisplaysRouteRouteWithChildren
  AdminLoginRoute: typeof AdminLoginRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminSurveysIndexRoute: typeof AdminSurveysIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminDisplaysRouteRoute: AdminDisplaysRouteRouteWithChildren,
  AdminLoginRoute: AdminLoginRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminSurveysIndexRoute: AdminSurveysIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface SetupRouteRouteChildren {
  SetupPendingRoute: typeof SetupPendingRoute
  SetupIndexRoute: typeof SetupIndexRoute
}

const SetupRouteRouteChildren: SetupRouteRouteChildren = {
  SetupPendingRoute: SetupPendingRoute,
  SetupIndexRoute: SetupIndexRoute,
}

const SetupRouteRouteWithChildren = SetupRouteRoute._addFileChildren(
  SetupRouteRouteChildren,
)

interface ApiAdminDisplaysDisplayIdRouteRouteChildren {
  ApiAdminDisplaysDisplayIdRevokeSessionRoute: typeof ApiAdminDisplaysDisplayIdRevokeSessionRoute
}

const ApiAdminDisplaysDisplayIdRouteRouteChildren: ApiAdminDisplaysDisplayIdRouteRouteChildren =
  {
    ApiAdminDisplaysDisplayIdRevokeSessionRoute:
      ApiAdminDisplaysDisplayIdRevokeSessionRoute,
  }

const ApiAdminDisplaysDisplayIdRouteRouteWithChildren =
  ApiAdminDisplaysDisplayIdRouteRoute._addFileChildren(
    ApiAdminDisplaysDisplayIdRouteRouteChildren,
  )

interface ApiAdminDisplaysEnrollmentsRouteRouteChildren {
  ApiAdminDisplaysEnrollmentsRequestIdApproveRoute: typeof ApiAdminDisplaysEnrollmentsRequestIdApproveRoute
  ApiAdminDisplaysEnrollmentsRequestIdRejectRoute: typeof ApiAdminDisplaysEnrollmentsRequestIdRejectRoute
}

const ApiAdminDisplaysEnrollmentsRouteRouteChildren: ApiAdminDisplaysEnrollmentsRouteRouteChildren =
  {
    ApiAdminDisplaysEnrollmentsRequestIdApproveRoute:
      ApiAdminDisplaysEnrollmentsRequestIdApproveRoute,
    ApiAdminDisplaysEnrollmentsRequestIdRejectRoute:
      ApiAdminDisplaysEnrollmentsRequestIdRejectRoute,
  }

const ApiAdminDisplaysEnrollmentsRouteRouteWithChildren =
  ApiAdminDisplaysEnrollmentsRouteRoute._addFileChildren(
    ApiAdminDisplaysEnrollmentsRouteRouteChildren,
  )

interface ApiAdminDisplaysRouteRouteChildren {
  ApiAdminDisplaysDisplayIdRouteRoute: typeof ApiAdminDisplaysDisplayIdRouteRouteWithChildren
  ApiAdminDisplaysEnrollmentsRouteRoute: typeof ApiAdminDisplaysEnrollmentsRouteRouteWithChildren
  ApiAdminDisplaysAuditLogsRoute: typeof ApiAdminDisplaysAuditLogsRoute
  ApiAdminDisplaysEnrollmentCodesRoute: typeof ApiAdminDisplaysEnrollmentCodesRoute
}

const ApiAdminDisplaysRouteRouteChildren: ApiAdminDisplaysRouteRouteChildren = {
  ApiAdminDisplaysDisplayIdRouteRoute:
    ApiAdminDisplaysDisplayIdRouteRouteWithChildren,
  ApiAdminDisplaysEnrollmentsRouteRoute:
    ApiAdminDisplaysEnrollmentsRouteRouteWithChildren,
  ApiAdminDisplaysAuditLogsRoute: ApiAdminDisplaysAuditLogsRoute,
  ApiAdminDisplaysEnrollmentCodesRoute: ApiAdminDisplaysEnrollmentCodesRoute,
}

const ApiAdminDisplaysRouteRouteWithChildren =
  ApiAdminDisplaysRouteRoute._addFileChildren(
    ApiAdminDisplaysRouteRouteChildren,
  )

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  SetupRouteRoute: SetupRouteRouteWithChildren,
  ThrowErrorRoute: ThrowErrorRoute,
  DisplayDisplayIdRoute: DisplayDisplayIdRoute,
  RueckmeldungDisplayIdRoute: RueckmeldungDisplayIdRoute,
  ApiAdminDisplaysRouteRoute: ApiAdminDisplaysRouteRouteWithChildren,
  ApiAdminSurveysRoute: ApiAdminSurveysRoute,
  ApiCalendarEventsRoute: ApiCalendarEventsRoute,
  ApiDisplaysSessionRoute: ApiDisplaysSessionRoute,
  ApiSubstitutionPlansRoute: ApiSubstitutionPlansRoute,
  ApiSurveysSubmissionsRoute: ApiSurveysSubmissionsRoute,
  ApiAdminAuthCredentialsRoute: ApiAdminAuthCredentialsRoute,
  ApiAdminAuthCsrfRoute: ApiAdminAuthCsrfRoute,
  ApiAdminAuthLoginRoute: ApiAdminAuthLoginRoute,
  ApiAdminAuthLogoutRoute: ApiAdminAuthLogoutRoute,
  ApiAdminAuthMeRoute: ApiAdminAuthMeRoute,
  ApiDisplaysEnrollmentsRequestIdRoute: ApiDisplaysEnrollmentsRequestIdRoute,
  ApiSurveysDisplaysDisplayIdRoute: ApiSurveysDisplaysDisplayIdRoute,
  ApiTransportStopsNearbyRoute: ApiTransportStopsNearbyRoute,
  ApiDisplaysEnrollmentsIndexRoute: ApiDisplaysEnrollmentsIndexRoute,
  ApiTransportStopsStopIdDeparturesRoute:
    ApiTransportStopsStopIdDeparturesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
