/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ThrowErrorRouteImport } from './routes/throw-error'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DisplayScreenIdRouteImport } from './routes/display.$screenId'
import { Route as ApiSubstitutionPlansRouteImport } from './routes/api.substitution.plans'
import { Route as ApiCalendarEventsRouteImport } from './routes/api.calendar.events'

const ThrowErrorRoute = ThrowErrorRouteImport.update({
  id: '/throw-error',
  path: '/throw-error',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayScreenIdRoute = DisplayScreenIdRouteImport.update({
  id: '/display/$screenId',
  path: '/display/$screenId',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSubstitutionPlansRoute = ApiSubstitutionPlansRouteImport.update({
  id: '/api/substitution/plans',
  path: '/api/substitution/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiCalendarEventsRoute = ApiCalendarEventsRouteImport.update({
  id: '/api/calendar/events',
  path: '/api/calendar/events',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/throw-error': typeof ThrowErrorRoute
  '/display/$screenId': typeof DisplayScreenIdRoute
  '/api/calendar/events': typeof ApiCalendarEventsRoute
  '/api/substitution/plans': typeof ApiSubstitutionPlansRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/throw-error': typeof ThrowErrorRoute
  '/display/$screenId': typeof DisplayScreenIdRoute
  '/api/calendar/events': typeof ApiCalendarEventsRoute
  '/api/substitution/plans': typeof ApiSubstitutionPlansRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/throw-error': typeof ThrowErrorRoute
  '/display/$screenId': typeof DisplayScreenIdRoute
  '/api/calendar/events': typeof ApiCalendarEventsRoute
  '/api/substitution/plans': typeof ApiSubstitutionPlansRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/throw-error'
    | '/display/$screenId'
    | '/api/calendar/events'
    | '/api/substitution/plans'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/throw-error'
    | '/display/$screenId'
    | '/api/calendar/events'
    | '/api/substitution/plans'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/throw-error'
    | '/display/$screenId'
    | '/api/calendar/events'
    | '/api/substitution/plans'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ThrowErrorRoute: typeof ThrowErrorRoute
  DisplayScreenIdRoute: typeof DisplayScreenIdRoute
  ApiCalendarEventsRoute: typeof ApiCalendarEventsRoute
  ApiSubstitutionPlansRoute: typeof ApiSubstitutionPlansRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/throw-error': {
      id: '/throw-error'
      path: '/throw-error'
      fullPath: '/throw-error'
      preLoaderRoute: typeof ThrowErrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/display/$screenId': {
      id: '/display/$screenId'
      path: '/display/$screenId'
      fullPath: '/display/$screenId'
      preLoaderRoute: typeof DisplayScreenIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/substitution/plans': {
      id: '/api/substitution/plans'
      path: '/api/substitution/plans'
      fullPath: '/api/substitution/plans'
      preLoaderRoute: typeof ApiSubstitutionPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/calendar/events': {
      id: '/api/calendar/events'
      path: '/api/calendar/events'
      fullPath: '/api/calendar/events'
      preLoaderRoute: typeof ApiCalendarEventsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ThrowErrorRoute: ThrowErrorRoute,
  DisplayScreenIdRoute: DisplayScreenIdRoute,
  ApiCalendarEventsRoute: ApiCalendarEventsRoute,
  ApiSubstitutionPlansRoute: ApiSubstitutionPlansRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
